### ISSUE TITLE
Backward Compatibility

### ISSUE THREAD

**Issue by patelakshay13890** [d-max/spots-dialog#1]
Will work with 2.2 Android Version or later ??

**Comment by d-max** [comment]
Hello, patelakshay13890!
No, it won't. It uses AnimatorSet and Interpolator classes. They have been provided since api level 11

**Comment by alorma** [comment]
In fact, Support Libraries give Interpolators with NineOldAndroid classes

**Comment by d-max** [comment]
You are right. But I can't see any reason to support devices with api level < 15 :)
