### ISSUE TITLE
Dialog animation for pre-Lollipop (Android 4.3)

### ISSUE THREAD

**Issue by GarciaPL** [d-max/spots-dialog#10]
Hi,

I am using your library in Android app which is compiled to Android SDK version 23. I am running this app on Android 4.3. As far I can see the title of dialog, but I cannot see the animation composed from dots. My style.xml configuration looks like this one :

    <style name="LoadingDialog" parent="android:Theme.DeviceDefault.Dialog">
        <item name="DialogTitleAppearance">@android:style/TextAppearance.Medium</item>
        <item name="DialogTitleText">Loading</item>
        <item name="DialogSpotCount">4</item>
    </style>
    <color name="spots_dialog_color">@color/nliveo_orange_colorPrimary</color>

Could you give me some additional guidance how fix this issue ? Thanks in advance!

**Comment by d-max** [comment]
Hi!
Thank you for your contribution. I will check out this issue and let you know.

**Comment by d-max** [comment]
Sorry, can't reproduce at my 4.3 device. It works.
I used your style and created dialog like this:
```
new SpotsDialog(this, R.style.LoadingDialog).show();
```

**Comment by d-max** [comment]
Do you use proguard ?

**Comment by GarciaPL** [comment]
Yes I use proguard. Funny thing is that your library works on genymotion, but I have issue on real device.

**Comment by GarciaPL** [comment]
I saw somewhere in logs which might be related with issue :+1: 

Could not find method android.widget.FrameLayout.<init>, referenced from method dmax.dialog.ProgressLayout.<init>

**Comment by d-max** [comment]
Well, first, try to add these lines into you caustom proguard config file to avoid any shrinks:
```
-keep class dmax.dialog.** {
    *;
}
```

Next, can you add here whole stack-trace?
I will prepare some build for you, compiled with build tools 22.

**Comment by d-max** [comment]
Try to use verison build with build tools 22
```
compile 'com.github.d-max:spots-dialog:0.6-bt22'
```
It will be available in 2-3 hours

**Comment by d-max** [comment]
Hi, Lukasz! How is it going with this problem?

**Comment by GarciaPL** [comment]
I was not be able to fix it and unfortunately I used standard android's ProgressDialog. Thanks for help, but it was force majeure. Thanks for your help!

**Comment by d-max** [comment]
Okay, I see. Tell me please one more thing. Did you try this 6-bt22 version?

**Comment by GarciaPL** [comment]
I remember that I was trying but without success.

**Comment by d-max** [comment]
Okay. Thanks

**Comment by jongha** [comment]
I have same issue in 4.4.3 nexus.

**Comment by jongha** [comment]
Finally I found a solution.

Change public class (HesitateInterpolator, AnimatorPlayer, AnimatedView)

or

Keep these three class in proguard rule.

Thanks!

**Comment by d-max** [comment]
Hi, 
thanks for reply. I wrote proguard rules at blogspot article. I think, I need to add the same to readme file here.
