### ISSUE TITLE
How to set message programatically?

### ISSUE THREAD

**Issue by Dharma237** [d-max/spots-dialog#12]
I am trying to add message through the string using this code 

  public static SpotsDialog showProgressDialog(Context context, final String message) throws NullPointerException {

        if (context != null) {
            SpotsDialog dialog = new SpotsDialog(context, R.style.dialog);
            dialog.setMessage(message);
            return dialog;
        }
        return  null;

    }

But message shows  as "?21301234".

Can you help me out from this problem?

**Comment by d-max** [comment]
Hi.
If you want to set custom message for this dialog, you can use two ways:
1. Constructor
```
new SpotsDialog(context, message, style);
```
2. setMessage() method
```
SpotsDialog dialog = new SpotsDialog(this);
dialog.show();
dialog.setMessage("Custom title");
```
