### ISSUE TITLE
setMessage not working

### ISSUE THREAD

**Issue by meeftah** [d-max/spots-dialog#13]
hi, I'm using your spots-dialog for my project...but setMessage() is not working...
this is my code:
```
SpotsDialog dialog = new SpotsDialog(this, R.style.Custom);
        dialog.setTitle("testing...");
        dialog.show();
```

instead of "testing..." I got "?2130772112", or I just being don't understand with constructor, 

and I've tried you second solution:
```
SpotsDialog dialog = new SpotsDialog(this);
        dialog.show();
        dialog.setMessage("testing...");
```
but, instead of custom message that I've set, I got "Loading..." message. Please your guidance...

**Comment by d-max** [comment]
Hi, please consider issue #12

**Comment by meeftah** [comment]
Hi, thanks for the reply....it works
all I have to do was just change version from 0.4 to the latest version, please update your usage section to avoid new issue with message problem

btw, it's really good alert dialog, thanks for sharing...

**Comment by d-max** [comment]
Hi, Meeffah
Great :) 
I suggest you to use version 0.7. setMessage() method is fixed there.

**Comment by sanctifie** [comment]
hi i'm using your spots dialog for my android project but AlertDialog is not working
incompatible types. Fuund 'dmax.dialog.';required: 'android.support.v7.app.AlertDialog'

**Comment by d-max** [comment]
Hi @sanctifie You need to import `android.app.AlertDialog` class

**Comment by KristoofCDMX** [comment]
Hello @d-max , I'm using too your SpotDialog for my android project and I have the next mistake:

Incompatible Types.
Required: **android.support.v7.app.Alert-Dialog**
Found: **dmax.dialog.SpotsDialog**
