### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by lazar108** [d-max/spots-dialog#14]
I spent an unnecessary time trying to figure out the .setMessage issue when all I had to do was change `compile 'com.github.d-max:spots-dialog:0.4@aar'` to `compile 'com.github.d-max:spots-dialog:0.7@aar'`. Update this so other people don't make the same mistake 

ps. great dialog! +1

**Comment by d-max** [comment]
@lazar108 sorry, man :) Thanks for reminder. Will do
