### ISSUE TITLE
DialogSpots not showing up

### ISSUE THREAD

**Issue by erkand-imeri** [d-max/spots-dialog#16]
Hello there i am having an issue with the SpotsDialog, the box shows up but not the DialogSpotCount, i have already implemented it before and everything  was ok, i changed a bit  of code(not sure but i think the xml themes).

What's the problem with it and how can i solve it. 

I implemented the same code just  as the instructions are given. Any help?

**Comment by erkand-imeri** [comment]
Could it be that the spots are not shown up because i have used Proguard shrink and minify?  I read somewhere about this.

**Comment by d-max** [comment]
Hi, @erkand-imeri Sorry for late response. It looks like proguard removed unused resources. Please, take a look at readme or #10. Thanks
