### ISSUE TITLE
Dialog width and Height ?

### ISSUE THREAD

**Issue by yusuf77kenan** [d-max/spots-dialog#17]
Hey There. I have a issue with apots-dialog. I would like to change width and height ?.

I would appreciate if you can help Good Work.

**Comment by d-max** [comment]
Hi, @yusuf77kenan. Thanks. This is just standard dialog. So, you can add any styles attribute, you want. To set dialog size use `<item name="android:minHeight">Xdp</item>` and `<item name="android:minWidth">Xdp</item>` in style xml.
