### ISSUE TITLE
is there an easy way to change the color for the title ?

### ISSUE THREAD

**Issue by justaaq** [d-max/spots-dialog#19]
is there an easy way to change the color for the title ?

Currently it is by default using the colorPrimary , can i change it to another color like white for example .
you provided the following for customizing
DialogTitleAppearance
DialogTitleText
DialogSpotColor
DialogSpotCount

non of them can be used for this .

**Comment by eGorets** [comment]
It would be nice.
@justaaq For now I used this workaround:

```
        loader.show()

        val textView = loader.findViewById(R.id.dmax_spots_title) as TextView
        textView.textColor = ContextCompat.getColor(context, R.color.white)
```

I hope it will help you as well

**Comment by justaaq** [comment]
Awesome workaround @eGorets 
Many thanks to you ,one note though i think that you are using swift syntax for your code snippet .
for the same workaround but in java i use this method 

public static AlertDialog showProgressDialog(Context context, String message) {
        AlertDialog dialog = new SpotsDialog(context, message, R.style.dialog_spot_style);
        dialog.setCancelable(false);
        dialog.show();
        TextView textView = (TextView)dialog.findViewById(R.id.dmax_spots_title);
        if(textView!=null) {
            textView.setTextColor(ContextCompat.getColor(context, R.color.white));
        }
        return dialog;
    }

**Comment by eGorets** [comment]
@justaaq `Kotlin`. It's realy cool language, try it too, you will be impressed

**Comment by d-max** [comment]
Hi, guys! Thanks for feedback. I will add such attribute. And yes, Kotlin is amazing! :)

**Comment by d-max** [comment]
Hi guys. Sorry for late response.
I believe you can use `DialogTitleAppearance` to customize color and other properties of title textview
