### ISSUE TITLE
Include id Resource  instead only raw string

### ISSUE THREAD

**Issue by collura** [d-max/spots-dialog#25]
What do you think to put  another SpotsDialog constructor with Id Resource to take the parameter smaller when we create or setMessage besides be good practice ? I only to get pass strings directly.

Something so:

```
   public SpotsDialog(Context context, int message) {
        this(context);
        this.message = context.getResources().getString(message);
    }

```
Thanks.

**Comment by d-max** [comment]
Hi, @collura! Thanks for suggestion. I'll add new constructor with Ids

**Comment by d-max** [comment]
Hi, sorry for late response. Actually, you need to use `SpotsDialog.Builder` class. So you can pass message resource id
