### ISSUE TITLE
Minor issue with long texts

### ISSUE THREAD

**Issue by FANMixco** [d-max/spots-dialog#26]
I think your library is awesome :D! However, there is one minor improvement point:

```XML 
<TextView
        android:id="@+id/dmax_spots_title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/title_margin"
        android:layout_gravity="center"
        android:textAppearance="?attr/DialogTitleAppearance"
        android:text="?attr/DialogTitleText"/>
```

The layout_width should be match_parent, if it's wrap_content and the text is too long for X or Y reason, it stops working as expected and it goes to the left. Maybe you could update it in your free time! Thanks for so awesome library.

**Comment by d-max** [comment]
Hi, @FANMixco! Thanks for feedback and for suggestion. I'll check it out and make new build

**Comment by d-max** [comment]
Hi. I've checked and `layout_width` is already `match_parent`
