### ISSUE TITLE
setMessage

### ISSUE THREAD

**Issue by oarage** [d-max/spots-dialog#32]
dialog.setMessage("loading...");
call setMessage method crash

**Comment by TariqMahmd** [comment]
You can change message in custom theme

**Comment by ntsparis** [comment]
Try setMessage before build dialog like:

new SpotsDialog.Builder()
                        .setContext(this)
                        .setTheme(R.style.Custom)
                        .setMessage("loading...)
                        .build()
.show();

**Comment by d-max** [comment]
@oarage It crashes when you call `dialog.setMessage` before `dialog.show`. Please use `SpotsDialog.Builder` for that.
