### ISSUE TITLE
moving spots not showing when enabling proguard

### ISSUE THREAD

**Issue by hishamtbox** [d-max/spots-dialog#33]
When we enable the pro guard (to shrink code files and resources),  the moving spots or dots disappears. No animation, only dialog with message is showing. Attached a screenshot as well, any help will be much appreciated.
![screen shot 2018-04-12 at 1 30 59 pm](https://user-images.githubusercontent.com/32865457/38665426-cd818c42-3e55-11e8-9bd2-76e01e656ad4.png)

**Comment by d-max** [comment]
Please, add next lines to your proguard config file:
```
-keep class dmax.dialog.** {
    *;
}
```
