### ISSUE TITLE
I removed this and still gives error in cache files

### ISSUE THREAD

**Issue by developer20atmoderni** [d-max/spots-dialog#34]
I removed this from my gradle in android studio3.0.1 but still project is not syncing  by giving me the error in cache files
C:\Users\Moderni\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.1.aar\e8ddbb4d66d9a9dbbaff29cb1e3cc03d\res\values\values.xml 

Error:(1423, 5) error: style attribute 'attr/DialogTitleAppearance (aka com.kiran.example.ebitcoin:attr/DialogTitleAppearance)' not found.

**Comment by d-max** [comment]
I am not sure I can help to deal with android studio. Try clean/rebuild project.

**Comment by developer20atmoderni** [comment]
I have done all these things, done Invalidate cache and restart too but still facing the issue
