### ISSUE TITLE
Readme should be updated with the working library

### ISSUE THREAD

**Issue by hoornet** [d-max/spots-dialog#37]
It should say: 
implementation 'com.github.d-max:spots-dialog:1.0'
instead of the old 0.7 version.

Also example is wrong now. It should include the Builder like this:
        val progressDlg = SpotsDialog.Builder()
                .setContext(this)
                .setTheme(R.style.Custom)
                .setMessage("Trying to log in...")
                .build()
        progressDlg.show()
or something along these lines.

**Comment by d-max** [comment]
thanks. updated
