### ISSUE TITLE
SpotsDialog(....) has private access in 'dmax.dialog.SpotsDialog'

### ISSUE THREAD

**Issue by d3smondwong** [d-max/spots-dialog#39]
Hi, 

tried the following

  AlertDialog waitingDialog = new SpotsDialog(LogIn.this);

but SpotsDialog can't be read. Any idea what am i missing?

The android prompt put this as the error SpotsDialog(....) has private access in 'dmax.dialog.SpotsDialog'

**Comment by dybarsky** [comment]
Hi,
please, use builder:
```
val dialog: AlertDialog = SpotsDialog.Builder().setContext(context).build()
...
dialog.show()
...
dialog.dismiss()
```

**Comment by amansrii8** [comment]
**_SpotsDialog.Builder()_**.setContext(context).build() says method call required in java
