### ISSUE TITLE
private access in dmx.dialog.SpotsDialog

### ISSUE THREAD

**Issue by Ponkabonk** [d-max/spots-dialog#42]
SpotsDialog dialog;
dialog = new SpotsDialog(this);

0.7 works great.  I tried upgrading to 1.1 and keep getting a "private" access error.  Can you provide a Java example?
![error](https://user-images.githubusercontent.com/4604965/46442693-6a87d300-c71f-11e8-9cc3-bd0f81db1893.PNG)

**Comment by dybarsky** [comment]
The usage is described in readme.
```
val dialog: AlertDialog = SpotsDialog.Builder()
    .Builder()
    .setContext(context)
    .setTheme(R.style.Cusom)
    .build()
    .apply {
        show()
    }
```

**Comment by Ponkabonk** [comment]
I saw that.  Unfortunately, it doesn't seem to work when you convert that to Java and use v1.1.

Sent from my Android device.

-----Original Message-----

**Comment by dybarsky** [comment]
"Not working" doesn't really make sense. Is it crashing? Is it showing? Compile error?
This works to me
```
AlertDialog dialog = new SpotsDialog.Builder()
                .setContext(this)
                .setMessage("tes")
                .setCancelable(false)
                .build();

        dialog.show();
```

**Comment by Ponkabonk** [comment]
OK.  I got it working.  Thanks for pointing me in the right direction.


-Mike
