### ISSUE TITLE
Progressbar in Spotdialog not showing in Android M(API 23) and Android P(API 28).

### ISSUE THREAD

**Issue by Smarpit-Singh** [d-max/spots-dialog#47]
Test on real device and Emulator also, But progressbar is not visible

![InkedScreenshot_2019-03-27-19-04-54-03 (1)_LI](https://user-images.githubusercontent.com/27909804/55083205-20c5e700-50c9-11e9-9936-c9502456de66.png)

**Comment by dybarsky** [comment]
Hi @Smarpit-Singh. Post here use code

**Comment by Smarpit-Singh** [comment]
`AlertDialog progressBar;`

    progressBar = new SpotsDialog.Builder()
                .setContext(this)
                .setMessage("Checking for update")
                .setTheme(R.style.AppCompatAlertDialogStyle)
                .setCancelable(true)
                .build();


## Style.xml
      <style name="AppCompatAlertDialogStyle" parent="@android:style/Theme.Holo.Dialog">
        <item name="android:windowBackground">@color/colorPrimaryDark</item>
        <item name="android:windowContentOverlay">@null</item>
    </style>
