### ISSUE TITLE
How change the title "Loading..."

### ISSUE THREAD

**Issue by josluimg** [d-max/spots-dialog#5]
I try it:

            dialogLoading = new SpotsDialog(getActivity());
            dialogLoading.setTitle("something");
             dialogLoading.setMessage("something");
            dialogLoading.show();

But the title doesn't change. Is "loading..." Do I should create a custom style to change the title? If I have got 20 diferent message I havo to create 20 styles?

Thanks your support

Even "loading..." is not i18n...

**Comment by josluimg** [comment]
I create this custom class:

    public class CustomSpotsDialog  extends SpotsDialog{

    String title;

    public CustomSpotsDialog(Context context, String title)
    {
        super(context);
        this.title = title;
    }


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if(title != null)
        {
            TextView text = (TextView) findViewById(R.id.title);

            if(text != null)
                text.setText(title);
        }
    }
    }

**Comment by d-max** [comment]
Hello!

Thanx for you participation. You are right, styles are not usefull in this case. I will fix that.
