### ISSUE TITLE
Is is possible to use SpotsDialog on androidX? 

### ISSUE THREAD

**Issue by Syetchau** [d-max/spots-dialog#51]
I have set the spotsDialog as below: 

final AlertDialog waitingDialog = new SpotsDialog.Builder()
                                                        .setContext(getBaseContext())
                                                        .setTheme(R.style.Custom)
                                                        .setCancelable(false)
                                                        .build();
                waitingDialog.show();

It give me a error such as: 
Incompatible types. Found: 'android.app.AlertDialog', required: 'androidx.appcompat.app.AlertDialog', is it possible to use on androidX?

**Comment by lucazbrandao** [comment]
Import AlertDialog from android.app.AlertDialog instead androidx.appcompat
