### ISSUE TITLE
Ability to define style and title both from constructor

### ISSUE THREAD

**Issue by zsoltk** [d-max/spots-dialog#7]
Hello and thanks for the great lib!

I think the dialog message should not be in the styles, as it doesn't have to do anything with the looks. When you have 5 different dialogs with the same style but different text, they all should use the same style.

I saw you closed a similar issue earlier and added a new constructor with context and message. The problem is that with this constructor you can't use a custom theme, so now you can set either the style OR the message.

The solution would be a constructor that allows setting both the style and the message message. If you agree, I'd happily contribute.

**Comment by d-max** [comment]
Added in v0.5

**Comment by susheel17** [comment]
when is v0.5 going to be released?

**Comment by d-max** [comment]
it is released.
